apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webapp-backend-deployment
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: "nginx:1.19.0"
        name: web-container
        ports:
        - containerPort: 80
          name: web-http
        volumeMounts:
        - mountPath: /logs
          name: example-volume
          subPath: logs-dir
        - mountPath: /errors
          name: example-volume
          subPath: errors-dir
        - mountPath: /data
          name: example-volume
          subPath: data-dir
      volumes:
      - name: example-volume
        persistentVolumeClaim:
          claimName: cet-efs
