apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-ebs-pv
  namespace: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.ebsVolumeId }}
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: db-ebs-pv
  storageClassName: ""