apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/example-webapp.git'
    targetRevision: {{ .Values.branch }}
    path: manifests/database
  destination:
    server: {{ .Values.cluster }}
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1  # Unlimited retries
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"