apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: monitoring
  template:
    metadata:
      labels:
        tier: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 8080
              name: grafana
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "newpassword"
            - name: GF_SERVER_HTTP_PORT
              value: "8080"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
