apiVersion: v1
kind: Service
metadata:
  name: monitoring-svc
  namespace: monitoring
spec:
  selector:
    tier: monitoring
  ports:
    - name: grafana
      protocol: TCP
      port: 8080
      targetPort: grafana