apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webapp-frontend-deployment
  namespace: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - image: "mariorgl/webapp-frontend:{{ .Values.image_tag }}"
          name: frontend-container
          ports:
            - containerPort: 80
              name: frontend-http