apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend
spec:
  selector:
    tier: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: frontend-http