name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Build and push Docker image
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp-frontend:${{ github.sha }} -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/webapp-frontend:${{ github.sha }}
